name: Dispatcher
defaults:
    user: flp
control:
    mode: fairmq
wants:
    cpu: 0.15
    memory: 128
bind:
    - name: from_Dispatcher_to_QC-TASK-RUNNER-QcTask
      type: push
      transport: shmem
      addressing: ipc
properties:
    color: "false"
    severity: trace
command:
    shell: true
    value: o2-qc-run-basic
    user: flp
    arguments:
        - -b
        - --dump-workflow
        - --dump-workflow-file
        - dpl-dump.json
