name: QC-CHECK-RUNNER-QcCheck
defaults:
    user: flp
control:
    mode: fairmq
wants:
    cpu: 0.15
    memory: 128
bind:
  - name: from_QC-CHECK-RUNNER-QcCheck_to_printer
    type: push
    transport: shmem
    addressing: ipc
properties:
    color: "false"
    severity: trace
command:
    shell: true
    value: |-
        eval `aliswmod load Control-OCCPlugin` &&
        o2-qc-run-basic
    user: flp
    arguments:
      - -b
      - --dump-workflow
      - --dump-workflow-file
      - dpl-dump.json
